// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Services.AutoRestClients.Facade
{
    using Models;

    /// <summary>
    /// </summary>
    public partial interface IFacadeClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        Newtonsoft.Json.JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        Microsoft.Rest.ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IPersonsAutoRest.
        /// </summary>
        IPersonsAutoRest PersonsAutoRest { get; }

        /// <summary>
        /// Gets the IPersonsHttpClient.
        /// </summary>
        IPersonsHttpClient PersonsHttpClient { get; }

    }
}
