// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Facade.AutoRestClients.Api.Models
{
    using System.Linq;

    public partial class Person
    {
        /// <summary>
        /// Initializes a new instance of the Person class.
        /// </summary>
        public Person() { }

        /// <summary>
        /// Initializes a new instance of the Person class.
        /// </summary>
        public Person(string email = default(string), string givenName = default(string), string id = default(string), string surName = default(string))
        {
            Email = email;
            GivenName = givenName;
            Id = id;
            SurName = surName;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "GivenName")]
        public string GivenName { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SurName")]
        public string SurName { get; set; }

    }
}
